import {
	Md10K,
	MdAbc,
	MdAllInbox,
	MdAnalytics,
	MdAnimation,
	MdApi, MdAutoAwesomeMosaic,
	MdAutoFixHigh,
	MdBrunchDining, MdCalculate,
	MdCarCrash,
	MdCasino,
	MdCelebration,
	MdCloudySnowing,
	MdConveyorBelt,
	MdCrisisAlert,
	MdCropRotate,
	MdDiversity2, MdElectricalServices,
	MdExpand,
	MdExplore, MdExtension, MdFactory, MdFilterBAndW, MdFilterHdr,
	MdHive,
	MdNetworkPing,
	MdOutline123,
	MdOutlineAirlineStops,
	MdOutlineAltRoute,
	MdOutlineCenterFocusStrong,
	MdOutlineCenterFocusWeak,
	MdOutlineCloseFullscreen,
	MdOutlineCompareArrows,
	MdOutlineCropOriginal,
	MdOutlineDeviceThermostat,
	MdOutlineDocumentScanner,
	MdOutlineEscalator,
	MdOutlineEventNote,
	MdOutlineFence,
	MdOutlineFilterFrames,
	MdOutlineFilterTiltShift,
	MdOutlineFullscreenExit,
	MdOutlineHardware,
	MdOutlineLensBlur,
	MdOutlineLocationSearching,
	MdOutlineMenuOpen,
	MdOutlineMerge,
	MdOutlineMergeType,
	MdOutlineMoveUp,
	MdOutlineNfc,
	MdOutlinePin,
	MdOutlineShutterSpeed,
	MdOutlineStarHalf,
	MdOutlineStream,
	MdOutlineSummarize,
	MdOutlineThermostat,
	MdPages,
	MdParagliding,
	MdPlumbing,
	MdPowerInput,
	MdSensorWindow,
	MdSwipeUpAlt,
	MdSwitchCamera,
	MdTableRows,
	MdTireRepair,
	MdTornado,
	MdTune,
	MdUpcoming,
	MdVignette,
	MdWater,
	MdZoomInMap
} from "react-icons/md";
import {FilterOptionType, languageData, sidebarLink} from "../../../shared/api/models.ts";
import {BiSortAlt2} from "react-icons/bi";
import {FaTape} from "react-icons/fa";
import {RiPassportFill} from "react-icons/ri";
import {AiFillSafetyCertificate} from "react-icons/ai";

/* Для отрисовки селектов на странице фильтра */
export const ru:  languageData = {
	productType: { title: "Тип продукции", icon: <MdHive />, type: FilterOptionType.TYPE_PRODUCT },
	type: { title: 'Тип изделия', icon: <MdOutlineDocumentScanner />, type: FilterOptionType.TYPE },
	o_comp: { title: 'Корпус или сборка', icon: <MdOutlineNfc />, type: FilterOptionType.OPTION },
	o_serie: { title: 'Серия', icon: <MdOutlinePin />, type: FilterOptionType.OPTION },
	o_sog: { title: 'Дополнительное покрытие', icon: <MdOutlineShutterSpeed />, type: FilterOptionType.OPTION },
	o_os: { title: 'Очистка под кислород', icon: <MdOutlineStream />, type: FilterOptionType.OPTION },
	o_bod_mat: { title: 'Основной материал', icon: <MdOutlineSummarize />, type: FilterOptionType.OPTION },
	o_col_mark: { title: 'Цвет брс', icon: <MdOutlineStarHalf />, type: FilterOptionType.OPTION },
	o_stem: { title: 'Тип иглы', icon: <MdParagliding />, type: FilterOptionType.OPTION },
	o_handle: { title: 'Тип рукоятки', icon: <MdPlumbing />, type: FilterOptionType.OPTION },
	o_surf: { title: 'Тип поверхности', icon: <MdPowerInput />, type: FilterOptionType.OPTION },
	o_seal: { title: 'Материал уплотнения', icon: <MdSwitchCamera />, type: FilterOptionType.OPTION },
	o_conf: { title: 'Геометрическая конфигурация изделия', icon: <MdSwipeUpAlt />, type: FilterOptionType.OPTION },
	o_fe: { title: 'Опция постоянной нагрузки у NV вентелей', icon: <MdTireRepair />, type: FilterOptionType.OPTION },
	o_panel: { title: 'Крепление на панель', icon: <MdTornado />, type: FilterOptionType.OPTION },
	o_345b: { title: 'Опция давления у NV', icon: <MdUpcoming />, type: FilterOptionType.OPTION },
	o_vent: { title: 'Опция дренажа', icon: <MdWater />, type: FilterOptionType.OPTION },
	o_plug: { title: 'Заглушка подсоединения', icon: <MdVignette />, type: FilterOptionType.OPTION },
	o_han_col: { title: 'Цвет рукоятки', icon: <MdAutoFixHigh />, type: FilterOptionType.OPTION },
	o_actu: { title: 'Тип привода', icon: <MdCarCrash />, type: FilterOptionType.OPTION },
	o_dn: { title: 'Нестандартное ДУ', icon: <MdCelebration />, type: FilterOptionType.OPTION },
	o_filt: { title: 'Тип фильтра', icon: <MdCasino />, type: FilterOptionType.OPTION },
	o_spri: { title: 'Тип пружины', icon: <MdExpand />, type: FilterOptionType.OPTION },
	o_ps: { title: 'Давление настройки клапана', icon: <Md10K />, type: FilterOptionType.OPTION },
	o_hp: { title: 'Опция высокого давления', icon: <MdConveyorBelt />, type: FilterOptionType.OPTION },
	o_len: { title: 'Опция длины фитинга', icon: <MdNetworkPing />, type: FilterOptionType.OPTION },
	o_shoul: { title: 'Опция плечиков у подсоединения у ZRC', icon: <MdOutlineAirlineStops />, type: FilterOptionType.OPTION },
	o_fusible: { title: 'Температура плавления защитного материала заглушки', icon: <MdOutlineDeviceThermostat />, type: FilterOptionType.OPTION },
	o_col: { title: 'Цвет у брс', icon: <MdOutlineCropOriginal />, type: FilterOptionType.OPTION },
	o_elem_mat: { title: 'Материал болтов и пластин', icon: <MdOutlineEscalator />, type: FilterOptionType.OPTION },
	o_bod_size: { title: 'Габаритные размеры зажима', icon: <MdOutlineEventNote />, type: FilterOptionType.OPTION },
	o_sec_mat: { title: 'Материал секции', icon: <MdOutlineFence />, type: FilterOptionType.OPTION },
	o_win_mat: { title: 'Материал окна', icon: <MdOutlineFilterFrames />, type: FilterOptionType.OPTION },
	o_spring_mat: { title: 'Материал чувствительного элемента', icon: <MdOutlineFilterTiltShift />, type: FilterOptionType.OPTION },
	o_rs: { title: 'Демпфер', icon: <MdOutlineHardware />, type: FilterOptionType.OPTION },
	o_cl: { title: 'Класс точности', icon: <MdOutlineLocationSearching />, type: FilterOptionType.OPTION },
	o_filling: { title: 'Заполнение', icon: <MdOutlineLensBlur />, type: FilterOptionType.OPTION },
	o_mp: { title: 'Указатель максимального давления', icon: <MdZoomInMap />, type: FilterOptionType.OPTION },
	o_scale_size: { title: 'Размер шкалы', icon: <MdTune />, type: FilterOptionType.OPTION },
	o_scale_unit1: { title: 'Единица измерения шкалы 1', icon: <MdOutline123 />, type: FilterOptionType.OPTION },
	o_scale_unit2: { title: 'Единица измерения шкалы 2', icon: <MdAbc />, type: FilterOptionType.OPTION },
	o_pointer_color: { title: 'Цвет указателя рабочего давления', icon: <MdAllInbox />, type: FilterOptionType.OPTION },
	o_bo: { title: 'Выдуваемая задняя стенка', icon: <MdAnimation />, type: FilterOptionType.OPTION },
	o_conn_conf: { title: 'Действие электроконтактов', icon: <MdAnalytics />, type: FilterOptionType.OPTION },
	o_ep: { title: 'Электрополировка', icon: <MdApi />, type: FilterOptionType.OPTION },
	o_bf: { title: 'Насечка под монтажный фланец', icon: <MdBrunchDining />, type: FilterOptionType.OPTION },
	o_ak: { title: 'Винт для найстройки', icon: <MdCrisisAlert />, type: FilterOptionType.OPTION },
	o_ve: { title: 'Поверка', icon: <MdCropRotate />, type: FilterOptionType.OPTION },
	o_microswitch: { title: 'Форма микропереключателей', icon: <MdDiversity2 />, type: FilterOptionType.OPTION },
	o_wateproof: { title: 'Влагозащита', icon: <MdCloudySnowing />, type: FilterOptionType.OPTION },
	connectionTypes1: { title: "Тип подсоединения 1", icon: <MdOutlineAltRoute />, type: FilterOptionType.CONNECTION_TYPE, index: 1},
	connectionTypes2: { title: "Тип подсоединения 2", icon: <MdOutlineCenterFocusStrong />, type: FilterOptionType.CONNECTION_TYPE, index: 2},
	connectionTypes3: { title: "Тип подсоединения 3", icon: <MdOutlineCloseFullscreen />, type: FilterOptionType.CONNECTION_TYPE, index: 3},
	connectionTypes4: { title: "Тип подсоединения 4", icon: <MdOutlineCompareArrows />, type: FilterOptionType.CONNECTION_TYPE, index: 4},
	connectionSizes1: { title: "Размер подсоединения 1", icon: <MdOutlineMenuOpen />, type: FilterOptionType.CONNECTION_SIZE, index: 1},
	connectionSizes2: { title: "Размер подсоединения 2", icon: <MdOutlineMerge />, type: FilterOptionType.CONNECTION_SIZE, index: 2},
	connectionSizes3: { title: "Размер подсоединения 3", icon: <MdOutlineMergeType />, type: FilterOptionType.CONNECTION_SIZE, index: 3},
	connectionSizes4: { title: "Размер подсоединения 4", icon: <MdOutlineMoveUp />, type: FilterOptionType.CONNECTION_SIZE, index: 4},
	minTemperature: { title: 'Мин температура рабочей среды', icon: <MdOutlineThermostat />, type: FilterOptionType.CHARACTERISTIC },
	// minPressure: { title: 'Мин давление настройки', icon: <MdOutlineFullscreenExit /> },
	cv: { title: 'Cv', icon: <MdSensorWindow />, type: FilterOptionType.CHARACTERISTIC },
	pressure: { title: 'Давление настройки', icon: <MdOutlineFullscreenExit />, type: FilterOptionType.CHARACTERISTIC },
	bodyPressure: { title: 'Рабочее давление', icon: <MdExplore />, type: FilterOptionType.CHARACTERISTIC },
	maxTemperature: { title: 'Макс температура рабочей среды', icon: <MdOutlineThermostat />, type: FilterOptionType.CHARACTERISTIC },
	// maxPressure: { title: 'Макс давление настройки', icon: <MdOutlineFullscreen /> },
	dn: { title: 'Dn', icon: <MdOutlineCenterFocusWeak />, type: FilterOptionType.CHARACTERISTIC },
	sort: { title: 'Сортировка', icon: <BiSortAlt2 />, default:  'rating'},
	outputList: { title: 'Вывод списка', icon: <BiSortAlt2 />, default:  'fld'},

	page: {title: 'Текущая страница', icon: <MdPages />, default: '1'},
	size: {title: 'Количество строк в таблице', icon: <MdTableRows />, default: '20'},
}

export const ruSidebarLinks: sidebarLink[] = [
	{
		title: 'Поиск по характеристикам',
		route: '',
		icon: <MdCalculate />
	},
	{
		title: 'Генерация тех паспортов',
		route: 'passport',
		icon: <AiFillSafetyCertificate />
	},
	{
		title: 'Форма закупщиков',
		route: 'test',
		icon: <MdElectricalServices />
	},
	{
		title: 'Обновить характеристики',
		route: 'test1',
		icon: <MdAutoAwesomeMosaic />
	},
	{
		title: 'Перезаписать файл конфигурации',
		route: 'test2',
		icon: <MdFilterHdr />
	},
	{
		title: 'Обновление базы данных',
		route: 'test3',
		icon: <MdFilterBAndW />
	},
	{
		title: 'Составление кодировки',
		route: 'test4',
		icon: <MdExtension />
	},
	{
		title: 'Краны и металлорукава',
		route: 'test5',
		icon: <FaTape />
	},
	{
		title: 'Паспорта для таможни',
		route: 'test6',
		icon: <RiPassportFill />
	},
	{
		title: 'Обновить таблицу опций',
		route: 'test7',
		icon: <MdFactory />
	},
]